### ISSUE TITLE
Add MIT License

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/Chrome-Extension#1]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by aditya5558** [comment]
claimed

**Comment by chainedcoder** [comment]
Can I do this?

**Comment by sbshah97** [comment]
@stevenkayter @aditya5558 claimed it first!
#5 Merged
