### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/Chrome-Extension#2]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Issues:
Create a link to the CONTRIBUTING.md file and the License file in the README file.
Change Code Status to working.

**Comment by Rishabh04-02** [comment]
what things you want to be added/deleted from the README.md

**Comment by sbshah97** [comment]
@Rishabh04-02 update the links to the other issues that'll be added. For example add the link of a License which will be added.

**Comment by sbshah97** [comment]
@Rishabh04-02 click on this [link](https://github.com/salman-bhai/TicTacToe/blob/master/README.md) to see a Standard README Format.

**Comment by sbshah97** [comment]
#6
